### ISSUE TITLE
Arrows are not correct

### ISSUE THREAD

**Issue by khashashin** [abulka/pynsource#110]
It creates same arrow for Aggregation and Composition. Here is sample Code:

```
# Aggregation
class Student:
    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id):
        return str(self._id) + '-' + department_id


class Department:
    def __init__(self, id, student):
        self._id = id
        self._student = student

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    student = Student(50)
    department = Department('ENG', student)

    print(department.student_registration())
```
---
```
# Composition
class Student:
    def __init__(self, id):
        self._id = id

    def registration_number(self, department_id):
        return str(self._id) + '-' + department_id


class Department:
    def __init__(self, department_id, student_id):
        self._id = department_id
        self._student = Student(student_id)

    def student_registration(self):
        return self._student.registration_number(self._id)


if __name__ == '__main__':
    department = Department('ENG', 50)

    print(department.student_registration())
```

![image](https://user-images.githubusercontent.com/17837758/167271917-19470dcc-7149-44f9-8711-62eed55727eb.png)

**Comment by abulka** [comment]
True, Pynsource doesn't distinguish between a class creating and 'owning' a relationship (composition) and a regular association (aggregation). 

In a dynamic language like Python its hard to figure out this distinction from just parsing Python source code. It also turns out that in UML practice, most users are either not aware of the distinction or don't care - they just care that a dependency relationship exists. Nothing wrong with wanting this feature though - it would be nice to have for people who care about it.

Aside: Check out the formal definition of [UML 2](https://www.omg.org/spec/UML/2.5.1/PDF). There are literally hundreds of nuances to UML which ended up leading to its downfall and to the downfall of modelling as a common tool for developers. Developers prefer to deal with text and when a class diagram is wanted, they just want the basic relationships.

I've actually come up with a UML alternative that is more useful to text based programmers. If you are interested you can read about it at [Literal Code Mapping](https://abulka.github.io/lcodemaps/).

**Comment by khashashin** [comment]
Well, if it was designed that way then it is not a bug and the issue can be closed.

LCM looks promising, btw I think UML was designed as a bridge between technical and less technical people, and LCM in my opinion is more for technical people, but can still be useful for less technical people with some overkill.
