### ISSUE TITLE
Cannot unlock pro version despite key

### ISSUE THREAD

**Issue by jgsuess** [abulka/pynsource#50]
Not nice, as I paid money and now don't have functionality.
```
Running Community Edition
Gtk-Message: 13:50:49.476: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:50:49.477: Failed to load module "canberra-gtk-module"
13:50:49: Debug: Adding duplicate image handler for 'PNG file'
13:50:49: Debug: Adding duplicate image handler for 'JPEG file'
13:50:49: Debug: Adding duplicate image handler for 'TIFF file'
13:50:49: Debug: Adding duplicate image handler for 'GIF file'
13:50:49: Debug: Adding duplicate image handler for 'PNM file'
13:50:49: Debug: Adding duplicate image handler for 'PCX file'
13:50:49: Debug: Adding duplicate image handler for 'IFF file'
13:50:49: Debug: Adding duplicate image handler for 'Windows icon file'
13:50:49: Debug: Adding duplicate image handler for 'Windows cursor file'
13:50:49: Debug: Adding duplicate image handler for 'Windows animated cursor file'
13:50:49: Debug: Adding duplicate image handler for 'TGA file'
13:50:49: Debug: Adding duplicate image handler for 'XPM file'
Traceback (most recent call last):
  File "/snap/pynsource/4/pynsource-gui.py", line 1277, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license'
connection error (no internet?) getting latest version info
user-open error: Object does not implement the interface
Traceback (most recent call last):
  File "/snap/pynsource/4/pynsource-gui.py", line 1277, in OnEnterLicense
    from gui.settings import enter_license
ImportError: cannot import name 'enter_license'
```

**Comment by jgsuess** [comment]
The system is behind a corporate proxy, but it has internet connection.

**Comment by jgsuess** [comment]
Unlock works on binary, but not on snap version on Ubuntu 16.04

**Comment by abulka** [comment]
Yes you need to use the binary version in order to activate the pro license. This is because there is no copy protection in snaps - something that the snapcraft team at Canonical should consider fixing, especially for something written in Python which has its source code exposed. I’m glad you got the binary registered ok. There will always be binary versions available for the major Ubuntu flavours. 

As for the corporate proxy internet issue - I’m happy to add something to help. I’m just using the famous Python requests package - so if there is a particular config you need I can add it to Pynsource.

**Comment by jgsuess** [comment]
I would recommend integrating PyPac, as you will find most companies use auto-proxy of some kind. https://pypac.readthedocs.io/en/latest/ PyPac claims to be interface compatible with requests. I really cannot use this without configuring proxy. And they will change wherever I log into the corp net.
In addition, it would be great if you could document what the reqs are on the PlantUML server, as a lot of  real clients will loath to send their designs over the internet and prefer to run a private instance if they buy the coverage license.

**Comment by jgsuess** [comment]
Final comment: Don't be discouraged by my input, please. I am just pointing out what you need for a product as opposed to a project. Given the uptick of interest in Python, you are doing the right thing at the right time. Not interesting stuff, product dev, but the reward is reputation, use and an income stream.

**Comment by abulka** [comment]
The latest master now contains support for pointing to your own plantuml server.  If there is an entry in
`~/.Pynsource/pynsource.ini` (for other platforms see  #49 for info re the location of pynsource.ini files) and if that file contains an entry e.g.

    PlantUmlServerUrl = http://localhost:8080/plantuml/uml

then that will be used as the Plantuml server url, otherwise the url defaults to the usual `http://www.plantuml.com/plantuml/uml`.  For instructions on installing PlantUML server see http://plantuml.com/server or otherwise google for advice.  I will eventually release another binary build with this feature, but for the moment, it is only available via this github repo / community edition mode.

> Not interesting stuff, product dev,

Huh?  A rather curious comment - was momentarily tempted to discuss but let's just stick to Pynsource issues!
