### ISSUE TITLE
Fails to render PlantUML behind corporate proxy

### ISSUE THREAD

**Issue by jgsuess** [abulka/pynsource#51]
The plantuml server is not accessible behind corporate proxy.

**Comment by abulka** [comment]
I initially thought that providing a proxy setting to the requests library would help with this till I realised I'm not using requests in Pynsource anymore - in favour of asyncronous calls - similar to this code:
https://gist.github.com/abulka/e27352615d0ba5bb36811278d801601f

I'm not familiar with corporate proxies technologies but would be willing to receive pull requests for any changes people might want to make to the open source Pynsource. 

See also related comments in #50.

**Comment by abulka** [comment]
Running your own local plantuml server is a workaround, which also has the benefits of being faster and also allows you to make bigger diagrams (the public plantuml server has a restriction on size).

Add a line to your `pynsource.ini` to point to your plantuml server e.g.:

```ini
PlantUmlServerUrl = http://localhost:8080/plantuml/uml
```
otherwise the plantuml server url defaults to the usual http://www.plantuml.com/plantuml/uml. 

## The location of `pynsource.ini`:

Windows:
`C:\Users\YOURNAME\AppData\Roaming\Pynsource\pynsource.ini`

Mac:
`~/Library/Preferences/Pynsource/pynsource.ini`
e.g.
/Users/YOURNAME/Library/Preferences/Pynsource/pynsource.ini

Linux:
`~/.Pynsource/pynsource.ini`

## To install a plantuml server
See official instructions here https://github.com/plantuml/plantuml-server

You can specify the port at which it runs:
`mvn jetty:run -Djetty.port=9999`
If so, then adust the `PlantUmlServerUrl` entry in `pynsource.ini` accordingly.

The following instructions are from my own notes and may help:

## To install a plantuml server on Linux Ubuntu

```
sudo apt install plantuml
sudo apt install maven
git clone https://github.com/plantuml/plantuml-server.git
cd plantuml-server
mvn jetty:run
```

and the server will  be running on localhost port 8080 and accessible via http://localhost:8080/plantuml/uml

## To install a plantuml server on Mac

```
brew install maven
git clone https://github.com/plantuml/plantuml-server
cd plantuml-server
mvn jetty:run
```

I haven't tried the above steps in a while though, and you *may* need these extra instructions:

You may need to install Java.  Install java using oracle using: `jdk-8u181-macosx-x64.dmg`. DO NOT install jdk-11_osx-x64_bin ??  Verify your Java installations with `ls /Library/Java/JavaVirtualMachines/`

You may need to install graphviz `brew install graphviz` and then set the environment variable `GRAPHVIZ_DOT=/usr/local/bin/dot; export GRAPHVIZ_DOT`. Verify with `java -jar plantuml.jar -testdot` to see a sample rendering.

Note: The open source community edition supports this local plantuml server feature. Version 1.74 does not. The beta of 1.75 does.
