### ISSUE TITLE
crash parsing Python **dict syntax

### ISSUE THREAD

**Issue by tinix84** [abulka/pynsource#65]
if I use the win10 1.3.5 with this file https://github.com/tinix84/pyplecs/blob/master/pyplecs/pyplecs.py it enter in endless loop.
what to do to debug it?

**Comment by abulka** [comment]
Hi. The code needs to compile. That code you refer to won’t compile because it’s indentation is all messed up, at least looking at the code via GitHub. 

cheers, 
Andy

**Comment by tinix84** [comment]
Thanks
can you please be more precise? the file run in VScode or in terminal, shoud I change something?

**Comment by abulka** [comment]
Hi - contrary to what I initially said, the code you refer to is actually formatted OK - it didn't appear formatted correctly when I initially browsed it in GitHub using my iPad Pro - probably some bug in Safari for iPad. Looks OK from a normal browser and when I downloaded that file.

Yes, I can confirm the code in module pyplecs.py is indeed causing a crash in Pynsource.  I will investigate. One laborious way you can figure out which line is causing the problem is to progressively edit and eliminate code in that module till the offending syntax is determined. 

Another way is to turn on parsing logging which I will document in the future, as I'll have to re-remember how to enable it!

FYI the online version of Pynsource (GitUML) parses this code OK straight from GitHub - you may be interested in GitUML as it specialises in your use case of parsing code from GitHub repos e.g. see https://www.gituml.com/viewz/100  

![gituml image svg](https://www.plantuml.com/plantuml/svg/TLHTQzim57tthr2pmjBHf6piARY6hOEyhAEix5aeqdMYLPQ4FffcO_zzrxBis6aQ2DQzz-X-71s9A-OzUL30_HThoT-2u8-Rfc5Qf3Mpjl_IRPHfJQdKCb0wlqgcXq1jcu7kv7P7hPF6oN38KMD1T-7iU99AJHpROJ-tCVjSrDJB9YeMfD5qSsYBvvWoJD1QAiWstm5_eh8URy3zMkej8luLHS6FKpw2UmQN1ssC0FM3DP3dQ4FTKZPK3tuqB0kxF4vu32xoS8w9t3N-zNPexxJTrkuxLyPFOAaX-ioSF-jzvHmXsrDuPYh2IIzx6NPKiC1ySC2QZf4n5HyMYugyDCfPlkHAWWxB75drb6G2rw31INvdD3e3k9JbNgZC9Wq7sp56QwD4flB8OvxZQDTHgS6Q4eiIj4PZBpwnqI5Yi77iQ4aTzezAdjGPoU9OUtfmb3gmRg9e0JMBAaoFv5zFXJqanPAon7XKK5Mu9FFxQ-FuJeehWevttvXxUWIsTW3wpDMopB4chJ2xr3qBtMm-C1Uw9ddJuK6BgKFua8H9pUPtnu6btl5-YU4-LUYcTh25bwwE4krC54MHR0txYQsaXg4rff46eRfaZazhBXQBaIXP64lTisSuzGd90mqct_Xstk4PG7LXfxGlsI56Mzz0O6lTqVI7ibmUNxGLKgu3azgJwXLWqFbvp9jwdsmeYlVVPKYDaJiK2xbdbZICE-EBugAEchVI8ms4dH7porQ2r-Go7Rw_dSsk2go4OYDbhCfDbUBbpQOgRs8rpx0hxAQumFFliuqJlpYevvS2VC2qJrABsrbhOE8BMPDvSf7RMpBp9ZeEw2-vKSQjVeAei6ZQsbOhRvA_mahAmnYL8KDO2rcVzdF9szcnJDxdp86fh_WULQMNVs3ryNCrowZD29Rk2DvEM3jswA6V1kXs13sFs9ojsKVjAFeG7Hxjk9s2umk30gYDQJ_hh2z1DWUobk5NeyX-lrzkPOYDMkBTBVu3)

**Comment by abulka** [comment]
Small update - seems Pynsource cannot understand the syntax 
```python
varin = {**self.optStruct['ModelVars'], **data}
```
on line 197.  By commenting out that single line, the file pyplecs.py parses OK. I'll need to improve the parser - are you running the Pynsource windows binary or running from source?  I can push a source code fix in Pynsource to GitHub pretty quickly.

**Comment by abulka** [comment]
Latest version of source code I just commited has better error reporting - you will get the line number and offending line of syntax displayed, plus an indication of where the log file is containing more information. a3baa972be687809fc64a3ba65234874c11d171e

Also now parses the above syntax without an error. 2728df81bf345906a042cc59c8480238bc95e09f

**Comment by tinix84** [comment]
thanks for your support! it works with github version :)
