### ISSUE TITLE
feature to report all methods as text

### ISSUE THREAD

**Issue by arita37** [abulka/pynsource#66]
Thanks for the tools.
Can you add the following ?
   Generate text file with all class, methods, functions signatures.
       myModule1.myClass2.mymethod(arg1, ...)
       myModule2.myClass3.mymethod(arg1, ...)

**Comment by abulka** [comment]
I've added this feature for you.

After importing Python code into Pynsource hit the 'D' key to dump the list of methods to the console. This only works for recently imported modules - if you quit Pynsource and then later load a diagram it will not have the needed information for the dump. You will also need to be running the latest master from a terminal, so that you can see console output.

I've also enhanced the Pynsource CLI with the `--methods-list` option to generate this report. Using the CLI you can more easily specify a list of Python files to scan, and it also works with wildcard specifications. This way of invoking the report will freshly scan the source code and thus always work and be accurate. E.g.

```bash
python3 ./src/pynsource-cli.py --methods-list a.py b.py
python3 ./src/pynsource-cli.py --methods-list src/common/command_pattern.py
python3 ./src/pynsource-cli.py --methods-list src/common/*.py
```

Unfortunately I currently do not record function signatures when scanning python source code, so all methods have no parameters in the report. To improve the parser to properly scan and record function signatures would involve enhancing the `def visit_FunctionDef` method of the file `src/parsing/core_parser_ast.py` and recording the information in the parse model into a new sub-list or something. Currently all I am recording is `self.current_class().defs.append(node.name)`.

Anyway, here is an example output from the CLI:
```
File: src/common/logger.py
--------------------------
logger.get_log_file_path()
logger.log_info()
logger.config_log()
logger.turn_off_logging()


File: src/common/logwriter.py
-----------------------------
logwriter.LogWriter.__init__()
logwriter.LogWriter.finish()
logwriter.LogWriter.out()
logwriter.LogWriter.out_divider()
logwriter.LogWriter.out_wrap_in_html()
logwriter.LogWriter.out_html_header()
logwriter.LogWriter.out_html_footer()

logwriter.LogWriterNull.__init__()
logwriter.LogWriterNull.finish()
logwriter.LogWriterNull.out()
logwriter.LogWriterNull.out_divider()
logwriter.LogWriterNull.out_wrap_in_html()
logwriter.LogWriterNull.out_html_header()
logwriter.LogWriterNull.out_html_footer()


File: src/common/messages.py
----------------------------

File: src/common/plantuml.py
----------------------------
plantuml.deflate_and_encode()
plantuml.encode()
plantuml._encode3bytes()
plantuml._encode6bit()

plantuml.PlantUML.__init__()
plantuml.PlantUML.get_url()
plantuml.PlantUML.processes()
plantuml.PlantUML.processes_file()

plantuml.PlantUMLHTTPError.__init__()


File: src/common/png.py
-----------------------
png.read_signature()
png.all_chunks()

png.Chunk.__init__()
png.Chunk.__repr__()
png.Chunk.write()
png.Chunk.read()
png.Chunk.create()

png.iTXtChunk.__init__()
png.iTXtChunk.create()
```
