### ISSUE TITLE
Sort elements

### ISSUE THREAD

**Issue by sjdowney** [abulka/pynsource#70]
Hi - this is more of a feature request, but it would be great to have an option to sort the names of class attributes before rendering the graphs (just to satisfy my OCD!).

Shane

**Comment by abulka** [comment]
Hmm, not a bad idea - will take a look.

**Comment by abulka** [comment]
Now implemented in master - 
4c331ee51f14321cf98f689ee84c7f3425c91e25

![2020-sorting-methods-attrs](https://user-images.githubusercontent.com/11467530/83101371-8bbbe500-a0f5-11ea-80be-9a663f27c1c0.png)

If you need a binary release, and are a pro customer, please let me know your OS and I'll generate a special beta for you with this enhancement in it.

P.S. Note that existing diagrams and built in sample diagrams will not be re-sorted - only new imports of code are sorted. Also when editing classes and adding methods/attrs etc. no additional sorting is applied so that the wishes of the user are respected.

**Comment by sjdowney** [comment]
Love your work Andy! Thanks for that :-)
